
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVISION = 13;
  public static final int DGLOBALES = 64;
  public static final int POTENCIA = 15;
  public static final int GPIE = 63;
  public static final int CORCHETEC = 61;
  public static final int CORCHETEA = 60;
  public static final int CATCH = 32;
  public static final int DISTINTO = 14;
  public static final int FALSE = 48;
  public static final int NOT = 19;
  public static final int MULTI = 10;
  public static final int CHAR_TYPE = 24;
  public static final int DOS_PUNTOS = 2;
  public static final int VALORES = 69;
  public static final int NUM = 54;
  public static final int PCOMA = 18;
  public static final int LLAVE_C = 5;
  public static final int LLAVE_A = 4;
  public static final int PARC = 22;
  public static final int CBOOL = 16;
  public static final int PARA = 21;
  public static final int INT_TYPE = 25;
  public static final int COMA = 3;
  public static final int WRITE = 47;
  public static final int TRUE = 44;
  public static final int NEWVALOR = 70;
  public static final int WHILE = 42;
  public static final int PORCENTAJE = 17;
  public static final int R_TITULO = 65;
  public static final int CHAR = 55;
  public static final int SWITCH = 37;
  public static final int DO = 33;
  public static final int FOR = 35;
  public static final int VOID = 29;
  public static final int PUBLIC = 40;
  public static final int RETURN = 41;
  public static final int ELSE = 34;
  public static final int TRY = 49;
  public static final int MENOS = 9;
  public static final int MAS = 8;
  public static final int BREAK = 30;
  public static final int DOT = 6;
  public static final int DOUBLE_TYPE = 27;
  public static final int MENORIK = 58;
  public static final int NULL = 38;
  public static final int EOF = 0;
  public static final int DEFAULT = 50;
  public static final int PRINT = 45;
  public static final int BOOL_TYPE = 26;
  public static final int CONSOLE = 46;
  public static final int MAIN = 23;
  public static final int OR = 12;
  public static final int error = 1;
  public static final int CONTINUE = 51;
  public static final int IF = 36;
  public static final int ID = 53;
  public static final int EJEX = 66;
  public static final int MENORK = 56;
  public static final int DISYUNCION = 7;
  public static final int MAYORK = 57;
  public static final int CASE = 31;
  public static final int DOLAR = 71;
  public static final int NEW = 39;
  public static final int STRING = 52;
  public static final int MAYORIK = 59;
  public static final int R_TITULOY = 68;
  public static final int R_TITULOX = 67;
  public static final int AND = 11;
  public static final int PRIVATE = 43;
  public static final int GBARRAS = 62;
  public static final int EQUALS = 20;
  public static final int STRING_TYPE = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOS_PUNTOS",
  "COMA",
  "LLAVE_A",
  "LLAVE_C",
  "DOT",
  "DISYUNCION",
  "MAS",
  "MENOS",
  "MULTI",
  "AND",
  "OR",
  "DIVISION",
  "DISTINTO",
  "POTENCIA",
  "CBOOL",
  "PORCENTAJE",
  "PCOMA",
  "NOT",
  "EQUALS",
  "PARA",
  "PARC",
  "MAIN",
  "CHAR_TYPE",
  "INT_TYPE",
  "BOOL_TYPE",
  "DOUBLE_TYPE",
  "STRING_TYPE",
  "VOID",
  "BREAK",
  "CASE",
  "CATCH",
  "DO",
  "ELSE",
  "FOR",
  "IF",
  "SWITCH",
  "NULL",
  "NEW",
  "PUBLIC",
  "RETURN",
  "WHILE",
  "PRIVATE",
  "TRUE",
  "PRINT",
  "CONSOLE",
  "WRITE",
  "FALSE",
  "TRY",
  "DEFAULT",
  "CONTINUE",
  "STRING",
  "ID",
  "NUM",
  "CHAR",
  "MENORK",
  "MAYORK",
  "MENORIK",
  "MAYORIK",
  "CORCHETEA",
  "CORCHETEC",
  "GBARRAS",
  "GPIE",
  "DGLOBALES",
  "R_TITULO",
  "EJEX",
  "R_TITULOX",
  "R_TITULOY",
  "VALORES",
  "NEWVALOR",
  "DOLAR"
  };
}

