
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadoresJson;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 4;
  public static final int COMA = 9;
  public static final int EOF = 0;
  public static final int LLAVE_C = 7;
  public static final int STRING = 2;
  public static final int LLAVE_A = 6;
  public static final int ID = 3;
  public static final int error = 1;
  public static final int DOS_PUNTOS = 8;
  public static final int CHAR = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "ID",
  "NUM",
  "CHAR",
  "LLAVE_A",
  "LLAVE_C",
  "DOS_PUNTOS",
  "COMA"
  };
}

